spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/database/digitquestdb
    username: userDigitQuest
    password: passwordDigitQuest
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    com.skazy.digitquest: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration: DEBUG