# ===== CONFIGURATION COMMUNE À TOUS LES ENVIRONNEMENTS =====

spring:
  application:
    name: digitquest
  profiles:
    active: dev

  # JPA
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # Configuration JSON commune
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Paris
    serialization:
      write-dates-as-timestamps: false


server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

# SpringDoc
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
  show-actuator: false

# Configuration Actuator de base
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized